module.exports = {
    redirectDomain : 'https://shippingcardao.herokuapp.com',
    clientDbEcommerce: 'mysql2',
    hostDbEcommerce: 'mongodb+srv://Jimmy:Daniela10@cluster0.qvbyu.mongodb.net/tesladb?retryWrites=true&w=majority',
    userDbEcommerce: 'admin',
    passwordDbEcommerce: 'Daniela10',
    dbEcommerce : 'ecommerce',
    driverClassName: 'mongo',
    hostSMTP: 'smtp.gmail.com',
    portSMTP: '465',
    userSTMP: 'ivallemol@gmail.com',
    passwordSTMP: 'enllfigmpwtpbudb',
    toMailAdmin: 'molina_valle@hotmail.com',
    accountTwilio: 'AC9633e06f21bc3c42dc1b583773dfa00f',
    tokenTwilio: '53900f72653d8d5a19c2549b834f80c1',
    phoneFromTwilio: '+14155238886',
    JWT_SECRET_SEED : 'Esto03Sun12DeMisToken@2034',
    PAYPAL_CLIENT_ID : 'AUm_rP4IsiXV3jFY7wdvxgTXTSpClAqNCokx_Rrl_aEx8utiBTT0GDlO64acEsFJ7I6MDxIKr5I_iZIM',
    PAYPAL_SECRET : 'ECtDvZ455ijKEgIZfM-nT6ld99Z_Aa_OcN0OOXN5zIKkdjAE8Mr8LjV12SggNv8jsL5zzgVfH2UmhRyQ',
    PAYPAL_OAUTH_URL : 'https://api-m.sandbox.paypal.com/v1/oauth2/token',
    PAYPAL_ORDERS_URL : 'https://api.sandbox.paypal.com/v2/checkout/orders',
    CLOUDINARY_CLOUD_NAME : 'do1uwxcks',
    CLOUDINARY_API_KEY : '543524287921487',
    CLOUDINARY_API_SECRET : 'XcBntg5ZHlrQ3V8wQl_i-2pxuvw'
  }